/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfitsRouteImport } from './routes/profits'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyIdRouteImport } from './routes/my-id'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as InvestPlanIdRouteImport } from './routes/invest.$planId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminInvestmentsRouteImport } from './routes/admin.investments'
import { Route as AdminExchangeRouteImport } from './routes/admin.exchange'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'
import { Route as AdminDepositInfoRouteImport } from './routes/admin.deposit-info'
import { Route as AdminBalancesRouteImport } from './routes/admin.balances'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitsRoute = ProfitsRouteImport.update({
  id: '/profits',
  path: '/profits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyIdRoute = MyIdRouteImport.update({
  id: '/my-id',
  path: '/my-id',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestPlanIdRoute = InvestPlanIdRouteImport.update({
  id: '/invest/$planId',
  path: '/invest/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvestmentsRoute = AdminInvestmentsRouteImport.update({
  id: '/admin/investments',
  path: '/admin/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExchangeRoute = AdminExchangeRouteImport.update({
  id: '/admin/exchange',
  path: '/admin/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/admin/deposits',
  path: '/admin/deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepositInfoRoute = AdminDepositInfoRouteImport.update({
  id: '/admin/deposit-info',
  path: '/admin/deposit-info',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBalancesRoute = AdminBalancesRouteImport.update({
  id: '/admin/balances',
  path: '/admin/balances',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/deposit': typeof DepositRoute
  '/exchange': typeof ExchangeRoute
  '/investment': typeof InvestmentRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/my-id': typeof MyIdRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/profits': typeof ProfitsRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/transfers': typeof TransfersRoute
  '/two-factor': typeof TwoFactorRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/balances': typeof AdminBalancesRoute
  '/admin/deposit-info': typeof AdminDepositInfoRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/exchange': typeof AdminExchangeRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/invest/$planId': typeof InvestPlanIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/deposit': typeof DepositRoute
  '/exchange': typeof ExchangeRoute
  '/investment': typeof InvestmentRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/my-id': typeof MyIdRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/profits': typeof ProfitsRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/transfers': typeof TransfersRoute
  '/two-factor': typeof TwoFactorRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/balances': typeof AdminBalancesRoute
  '/admin/deposit-info': typeof AdminDepositInfoRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/exchange': typeof AdminExchangeRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/invest/$planId': typeof InvestPlanIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/deposit': typeof DepositRoute
  '/exchange': typeof ExchangeRoute
  '/investment': typeof InvestmentRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/my-id': typeof MyIdRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/profits': typeof ProfitsRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/transfers': typeof TransfersRoute
  '/two-factor': typeof TwoFactorRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/balances': typeof AdminBalancesRoute
  '/admin/deposit-info': typeof AdminDepositInfoRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/exchange': typeof AdminExchangeRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/invest/$planId': typeof InvestPlanIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/deposit'
    | '/exchange'
    | '/investment'
    | '/kyc'
    | '/login'
    | '/my-id'
    | '/notifications'
    | '/profile'
    | '/profits'
    | '/register'
    | '/scan'
    | '/settings'
    | '/transactions'
    | '/transfers'
    | '/two-factor'
    | '/wallet'
    | '/withdraw'
    | '/admin/admins'
    | '/admin/agents'
    | '/admin/balances'
    | '/admin/deposit-info'
    | '/admin/deposits'
    | '/admin/exchange'
    | '/admin/investments'
    | '/admin/kyc'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/invest/$planId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/deposit'
    | '/exchange'
    | '/investment'
    | '/kyc'
    | '/login'
    | '/my-id'
    | '/notifications'
    | '/profile'
    | '/profits'
    | '/register'
    | '/scan'
    | '/settings'
    | '/transactions'
    | '/transfers'
    | '/two-factor'
    | '/wallet'
    | '/withdraw'
    | '/admin/admins'
    | '/admin/agents'
    | '/admin/balances'
    | '/admin/deposit-info'
    | '/admin/deposits'
    | '/admin/exchange'
    | '/admin/investments'
    | '/admin/kyc'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/invest/$planId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/deposit'
    | '/exchange'
    | '/investment'
    | '/kyc'
    | '/login'
    | '/my-id'
    | '/notifications'
    | '/profile'
    | '/profits'
    | '/register'
    | '/scan'
    | '/settings'
    | '/transactions'
    | '/transfers'
    | '/two-factor'
    | '/wallet'
    | '/withdraw'
    | '/admin/admins'
    | '/admin/agents'
    | '/admin/balances'
    | '/admin/deposit-info'
    | '/admin/deposits'
    | '/admin/exchange'
    | '/admin/investments'
    | '/admin/kyc'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/invest/$planId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DepositRoute: typeof DepositRoute
  ExchangeRoute: typeof ExchangeRoute
  InvestmentRoute: typeof InvestmentRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  MyIdRoute: typeof MyIdRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ProfitsRoute: typeof ProfitsRoute
  RegisterRoute: typeof RegisterRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  TransfersRoute: typeof TransfersRoute
  TwoFactorRoute: typeof TwoFactorRoute
  WalletRoute: typeof WalletRoute
  WithdrawRoute: typeof WithdrawRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminBalancesRoute: typeof AdminBalancesRoute
  AdminDepositInfoRoute: typeof AdminDepositInfoRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminExchangeRoute: typeof AdminExchangeRoute
  AdminInvestmentsRoute: typeof AdminInvestmentsRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  InvestPlanIdRoute: typeof InvestPlanIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profits': {
      id: '/profits'
      path: '/profits'
      fullPath: '/profits'
      preLoaderRoute: typeof ProfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-id': {
      id: '/my-id'
      path: '/my-id'
      fullPath: '/my-id'
      preLoaderRoute: typeof MyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest/$planId': {
      id: '/invest/$planId'
      path: '/invest/$planId'
      fullPath: '/invest/$planId'
      preLoaderRoute: typeof InvestPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/investments': {
      id: '/admin/investments'
      path: '/admin/investments'
      fullPath: '/admin/investments'
      preLoaderRoute: typeof AdminInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exchange': {
      id: '/admin/exchange'
      path: '/admin/exchange'
      fullPath: '/admin/exchange'
      preLoaderRoute: typeof AdminExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/admin/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deposit-info': {
      id: '/admin/deposit-info'
      path: '/admin/deposit-info'
      fullPath: '/admin/deposit-info'
      preLoaderRoute: typeof AdminDepositInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/balances': {
      id: '/admin/balances'
      path: '/admin/balances'
      fullPath: '/admin/balances'
      preLoaderRoute: typeof AdminBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DepositRoute: DepositRoute,
  ExchangeRoute: ExchangeRoute,
  InvestmentRoute: InvestmentRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  MyIdRoute: MyIdRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ProfitsRoute: ProfitsRoute,
  RegisterRoute: RegisterRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  TransfersRoute: TransfersRoute,
  TwoFactorRoute: TwoFactorRoute,
  WalletRoute: WalletRoute,
  WithdrawRoute: WithdrawRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminBalancesRoute: AdminBalancesRoute,
  AdminDepositInfoRoute: AdminDepositInfoRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminExchangeRoute: AdminExchangeRoute,
  AdminInvestmentsRoute: AdminInvestmentsRoute,
  AdminKycRoute: AdminKycRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  InvestPlanIdRoute: InvestPlanIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
